# Generated by Django 6.0.6 on 2026-07-11 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject",
                    models.CharField(help_text="Введите тему письма", max_length=250, verbose_name="Тема письма"),
                ),
                ("body", models.TextField(help_text="Введите полное содержание письма", verbose_name="Тело письма")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsLetterRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=250, unique=True, verbose_name="Email получателя")),
                (
                    "first_name",
                    models.CharField(help_text="Введите имя получателя", max_length=250, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Введите фамилию получателя", max_length=250, verbose_name="Фамилия"),
                ),
                (
                    "surname",
                    models.CharField(help_text="Введите отчество получателя", max_length=250, verbose_name="Отчество"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Введите комментарий о получателе", null=True, verbose_name="Комментарий"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="NewsLetter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Введите название рассылки",
                        max_length=200,
                        null=True,
                        verbose_name="Рассылка",
                    ),
                ),
                ("time_start", models.DateTimeField(verbose_name="дата и время первой отправки")),
                ("time_stop", models.DateTimeField(verbose_name="дата и время окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Cоздана"), ("launched", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите сообщение",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletters",
                        to="mailflow.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        help_text="Введите получателей",
                        related_name="recipients",
                        to="mailflow.newsletterrecipient",
                        verbose_name="Получатели",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ["-time_start"],
            },
        ),
        migrations.CreateModel(
            name="AttemptedMailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "time_mail",
                    models.DateTimeField(auto_now_add=True, verbose_name="дата и время попытки отправки отправки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")],
                        default="failed",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "response_server",
                    models.TextField(
                        blank=True,
                        help_text="Введите ответ от сервиса",
                        null=True,
                        verbose_name="Ответ почтового сервиса",
                    ),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите рассылку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="mailflow.newsletter",
                        verbose_name="Рассылка",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="mailflow.newsletterrecipient",
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
                "ordering": ["-time_mail", "status"],
            },
        ),
    ]
