# Generated by Django 6.0.6 on 2026-07-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(blank=True, help_text='Введите название рассылки', max_length=200, null=True, verbose_name='Рассылка'),
        ),
    ]
