# Generated by Django 6.0.6 on 2026-07-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailflow", "0002_newsletter_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[("created", "Cоздана"), ("launched", "Запущена"), ("completed", "Завершена")],
                default="created",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
