# Generated by Django 6.0.6 on 2026-07-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailflow", "0003_alter_newsletter_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="attemptedmailing",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipient",
                to="mailflow.newsletterrecipient",
                verbose_name="Получатель",
            ),
        ),
    ]
